using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using ClassLibrary2;

namespace WindowsFormsApp2
{
    public partial class Reciept : Form
    {
        public Reciept()
        {
            InitializeComponent();
        }

        private void richTextBox1_TextChanged(object sender, EventArgs e)
        {

        }

        private void Reciept_Load(object sender, EventArgs e)
        {
            reciepttxt.AppendText("Date = \t" + DateTime.Now.ToLongDateString() + Environment.NewLine);
            reciepttxt.AppendText("Reciept Generated by = " + WindowsFormsApp2.Program.username + Environment.NewLine);
            reciepttxt.AppendText(Environment.NewLine);
            reciepttxt.AppendText("--------------------------------------------------------------------------------------------------------" + Environment.NewLine);
            reciepttxt.AppendText("-------------------------------------Have a nice day!!---------------------------------------" + Environment.NewLine);
            reciepttxt.AppendText("--------------------------------------------------------------------------------------------------------" + Environment.NewLine);
            reciepttxt.AppendText(Environment.NewLine);
            reciepttxt.AppendText("Product Names\tProduct Quantity\tPrice Per Unit\tTotal" + Environment.NewLine);
            reciepttxt.AppendText("Apple\t\t" + WindowsFormsApp2.Program.qtyapple + "\t\t" + WindowsFormsApp2.Program.apple + "\t\t" + (WindowsFormsApp2.Program.qtyapple * WindowsFormsApp2.Program.apple) + Environment.NewLine);
            reciepttxt.AppendText("Samsung\t\t" + WindowsFormsApp2.Program.qtysamsung + "\t\t" + WindowsFormsApp2.Program.samsung + "\t\t" + (WindowsFormsApp2.Program.qtysamsung * WindowsFormsApp2.Program.samsung) + Environment.NewLine);
            reciepttxt.AppendText("Huawei\t\t" + WindowsFormsApp2.Program.qtyhuawei + "\t\t" + WindowsFormsApp2.Program.huawei + "\t\t" + (WindowsFormsApp2.Program.qtyhuawei * WindowsFormsApp2.Program.huawei) + Environment.NewLine);
            reciepttxt.AppendText("Vivo\t\t" + WindowsFormsApp2.Program.qtyvivo + "\t\t" + WindowsFormsApp2.Program.vivo + "\t\t" + (WindowsFormsApp2.Program.qtyvivo * WindowsFormsApp2.Program.vivo) + Environment.NewLine);
            reciepttxt.AppendText("Sony\t\t" + WindowsFormsApp2.Program.qtysony + "\t\t" + WindowsFormsApp2.Program.sony + "\t\t" + (WindowsFormsApp2.Program.qtysony * WindowsFormsApp2.Program.sony) + Environment.NewLine);
            reciepttxt.AppendText("Motorolla\t\t" + WindowsFormsApp2.Program.qtymotorolla + "\t\t" + WindowsFormsApp2.Program.motorolla + "\t\t" + (WindowsFormsApp2.Program.qtymotorolla * WindowsFormsApp2.Program.motorolla) + Environment.NewLine);
            reciepttxt.AppendText("OnePlus\t\t" + WindowsFormsApp2.Program.qtyoneplus + "\t\t" + WindowsFormsApp2.Program.oneplus + "\t\t" + (WindowsFormsApp2.Program.qtyoneplus * WindowsFormsApp2.Program.oneplus) + Environment.NewLine);
            reciepttxt.AppendText(Environment.NewLine);
            reciepttxt.AppendText("--------------------------------------------------------------------------------------------------------" + Environment.NewLine);
            reciepttxt.AppendText("Total\t\t\t\t\t\t" + WindowsFormsApp2.Program.total + Environment.NewLine);
        }

        private void txtclose_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void btnback_Click(object sender, EventArgs e)
        {
            PlaceOrder p = new PlaceOrder();
            p.Show();
            this.Hide();
            WindowsFormsApp2.Program.qtyapple = 0;
            WindowsFormsApp2.Program.qtysamsung = 0;
            WindowsFormsApp2.Program.qtyhuawei = 0;
            WindowsFormsApp2.Program.qtyvivo = 0;
            WindowsFormsApp2.Program.qtysony = 0;
            WindowsFormsApp2.Program.qtymotorolla = 0;
            WindowsFormsApp2.Program.qtyoneplus = 0;
        }
    }
}
